requires = [ "tox>=4.34.1", "tox-uv>=1.29" ]
env_list = [ "3.14", "3.13", "3.12", "3.11", "3.10", "docs", "fix", "pkg_meta", "type" ]
skip_missing_interpreters = true

[env_run_base]
description = "run the unit tests with pytest under {env_name}"
package = "wheel"
wheel_build_env = ".pkg"
dependency_groups = [ "test" ]
pass_env = [ "DIFF_AGAINST", "PYTEST_*" ]
set_env.COVERAGE_FILE = { replace = "env", name = "COVERAGE_FILE", default = "{work_dir}{/}.coverage.{env_name}" }
set_env.COVERAGE_PROCESS_START = "{tox_root}/pyproject.toml"
commands = [
  [
    "pytest",
    { replace = "posargs", extend = true, default = [
      "--junitxml",
      "{work_dir}{/}junit.{env_name}.xml",
      "--cov",
      "{env_site_packages_dir}{/}pyproject_api",
      "--cov",
      "{tox_root}{/}tests",
      "--cov-fail-under=100",
      "--cov-config=pyproject.toml",
      "--no-cov-on-fail",
      "--cov-report",
      "term-missing:skip-covered",
      "--cov-context=test",
      "--cov-report",
      "html:{env_tmp_dir}{/}htmlcov",
      "--cov-report",
      "xml:{work_dir}{/}coverage.{env_name}.xml",
      "tests",
    ] },
  ],
]

[env.docs]
description = "build documentation"
dependency_groups = [ "docs" ]
commands = [
  [
    "sphinx-build",
    "-d",
    "{env_tmp_dir}{/}doc_tree",
    "docs",
    "{env:READTHEDOCS_OUTPUT:{env_tmp_dir}{/}docs_out}/html",
    "--color",
    "-b",
    "html",
    "-W",
  ],
  [ "python", "-c", 'print(r"documentation available under file://{env_tmp_dir}{/}docs_out{/}index.html")' ],
]

[env.fix]
description = "run static analysis and style check using flake8"
package = "skip"
dependency_groups = [ "lint" ]
pass_env = [ "HOMEPATH", "PROGRAMDATA" ]
commands = [
  [ "pre-commit", "run", "--all-files", "--show-diff-on-failure" ],
  [ "python", "-c", 'print("hint: run {envdir}/bin/pre-commit install to add checks as pre-commit hook")' ],
]

[env.pkg_meta]
description = "check that the long description is valid"
skip_install = true
dependency_groups = [ "pkg-meta" ]
commands = [
  [ "uv", "build", "--sdist", "--wheel", "--out-dir", "{env_tmp_dir}", "." ],
  [ "twine", "check", "{env_tmp_dir}{/}*" ],
  [ "check-wheel-contents", "--no-config", "{env_tmp_dir}" ],
]

[env.type]
description = "run type check on code base"
dependency_groups = [ "type" ]
commands = [ [ "ty", "check", "--output-format", "concise", "--error-on-warning", "." ] ]

[env.dev]
description = "generate a DEV environment"
package = "editable"
dependency_groups = [ "dev" ]
commands = [
  [ "uv", "pip", "tree" ],
  [ "python", "-c", "import sys; print(sys.executable)" ],
]
